services:
  - type: web
    name: inwestor-2
    runtime: static
    plan: free
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
